/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

/**
 * ## 로직
 * ### 관리 데이터 리스트
 * - id : Long
 * - CarNumber : String
 * - PhoneNumber : String
 * - NearInTime\[최근 입차시간\] : LocalDateTime
 * - Amount : Int
 * - isPayment : Boolean
 * ### 행위
 * 1. 입차
 * 2. 출차
 * 3. 출력
 * 4. 수정
 * 5. 출차
 * 6. 종료
 */
public class App {
	static final int SIZE = 3;

	public static void main(String[] args) {
		System.out.println("차량 목록 관리 시스템");
		System.out.println("--------------------------------------------------------------------");

		// S : 선언부
		Scanner sc = new Scanner(System.in);
		Long[] id = new Long[SIZE];
		String[] carNumber = new String[SIZE];
		String[] phoneNumber = new String[SIZE];
		int[] amount = new int[SIZE];
		String[] parkingStartTime = new String[SIZE];
		boolean[] isPayment = new boolean[SIZE];

		//입력
		for (int i = 0; i < SIZE; i++) {
			id[i] = i + 1L;

			System.out.print("차량번호 입력 :");
			carNumber[i] = sc.nextLine();

			System.out.print("전화번호 입력 :");
			phoneNumber[i] = sc.nextLine();

			//Default 일단 1000으로 한다.
			amount[i] = 1000;

			parkingStartTime[i] = LocalDateTime.now()
				.format(DateTimeFormatter.ISO_INSTANT.ofPattern("yyyy-MM-dd HH:mm"));

			isPayment[i] = true;
		}

		for (int i = 0; i < 30; i++) {
			System.out.println();
		}

		System.out.println(
			String.format("%s\t%s\t%s\t%s\t%s\t%s",
				"번호", "차량번호", "휴대폰 전화번호", "주차 시작 시간", "주차비용", "결제여부"));
		System.out.println("--------------------------------------------------------------------");

		for (int i = 0; i < SIZE; i++) {
			System.out.print(
				String.format("%04d\t%s\t%s\t%s\t%s\t%s\n",
					id[i], carNumber[i], phoneNumber[i], parkingStartTime[i], amount[i], isPayment[i])
			);
		}

	}
}
