/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

/**
 * ## 로직
 * ### 관리 데이터 리스트
 * - id : Long
 * - CarNumber : String
 * - PhoneNumber : String
 * - NearInTime\[최근 입차시간\] : LocalDateTime
 * - Amount : Int
 * - isPayment : Boolean
 * ### 행위
 * 1. 입차
 * 2. 출차
 * 3. 출력
 * 4. 수정
 * 5. 출차
 * 6. 종료
 */
public class App {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		Long id = 1L;
		System.out.print("차량번호 입력 :");
		String carNumber = sc.nextLine();

		System.out.print("전화번호 입력 :");
		String phoneNumber = sc.nextLine();
		String parkingStartTime = LocalDateTime.now()
			.format(DateTimeFormatter.ISO_INSTANT.ofPattern("yyyy-MM-dd HH:mm"));
		int amount = 1000;
		boolean isPayment = false;

		System.out.println("나의 목록 관리 시스템");
		System.out.println("--------------------------------------------------------------------");
		System.out.println(
			String.format("%s\t%s\t%s\t%s\t%s\t%s",
				"번호", "차량번호", "휴대폰 전화번호", "주차 시작 시간", "주차비용", "결제여부"));

		System.out.print(
			String.format("%04d\t%s\t%s\t%s\t%s\t%s\n",
				id, carNumber, phoneNumber, parkingStartTime, amount, isPayment)
		);

	}
}
